# Generated by Django 6.0.4 on 2026-05-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_technologies_projectscreenshot_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
