# Generated by Django 6.0.4 on 2026-05-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
