# Generated by Django 6.0.4 on 2026-05-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.CharField(blank=True, choices=[('Web Dev', 'Web Development'), ('Python', 'Python Development'), ('ML', 'Machine Learning'), ('AI', 'Artificial Intelligence'), ('Java', 'Java Development')], max_length=100, null=True),
        ),
    ]
